### ISSUE TITLE
hr problems

### ISSUE THREAD

**Issue by zleonska** [en9inerd/zola-hacker#7]
Greetings!  I am very pleased with the theme and the cosmetic adaptions I have made. Thank-you!

One point has me baffled.

When I use < hr > *** ___  --- in markdown they all return a tiny dotted line

I have tried replacing all values in /sass/main.scss  under the hr {  but nothing changes. The original line separating post excerpts remains a heavy dash and my placed hr returns the light dotted line.

I even replaced it with an hr {  I know works

hr {
  width: 75%;
  height: 4px;
  display: block;
  margin-top: 30px;
  margin-bottom: 50px;
  border: none;
  background-color: #990000;
}

But nothing changes. ? For the life of me I can't figure out what I am missing.

Again thank-you for this lovely design.
Zuzanna

My original goal was to have a line with a small image in the centre for the index pages.  I've come to like the lighter dotted line in the individual posts and would like to keep that one.

**Comment by en9inerd** [comment]
Hello @zleonska,

The separator between post summaries is not controlled by `<hr>` element. Instead, it is styled using the `border-bottom` CSS property. You can find it defined in the following section of the stylesheet:

https://github.com/en9inerd/zola-hacker/blob/c48f02ef2915c93c2ddb579a6994db897ab4e156/sass/main.scss#L338

**Comment by en9inerd** [comment]
@zleonska 

> My original goal was to have a line with a small image in the centre for the index pages.

and this I think can be achieved using flex boxes.
something like this

```css
.separator {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 30px 0;
}

.separator::before,
.separator::after {
  content: "";
  flex: 1;
  height: 2px;
  background-color: #990000;
}

.separator img {
  margin: 0 10px;
  height: 20px; /* Adjust size as needed */
}
```

and in template somewhere after [this line](https://github.com/en9inerd/zola-hacker/blob/c48f02ef2915c93c2ddb579a6994db897ab4e156/templates/index.html#L26) you need to put this
```html
<div class="separator">
  <img src="your-image-url.png" alt="decorative separator">
</div>
```

**Comment by zleonska** [comment]
Thank-you so much. This worked better than I wished! I was chuffed to discover I can adjust the size of the image in css.

Unfortunately I must as one more question: looking at the main.scss border-bottom sections, I see no way to shorten the line segments for the index lines. And that wasn't a question! I think I meant to type, how do I shorten the line segments? 

I am very pleased with your theme! This is the first time I have been able proceed from installing the static generator (thanks to Zola, too!) to get a static web site up and online.

**Comment by zleonska** [comment]
If it would help you understand my crazy edits above here is a link to what I've been up to [:: zleonska ::](https://zleonska.dlpgraphics.ca)  

Kind of scary, adding a link 'Out There', but it might help you some...

**Comment by en9inerd** [comment]
@zleonska ok, let's go through each question! :)

> looking at the main.scss border-bottom sections, I see no way to shorten the line segments for the index lines. And that wasn't a question! I think I meant to type, how do I shorten the line segments?

Do you mean segments in solution that I provided? If yes then it can be fixed by `width` property like that:
```css
.separator::before,
.separator::after {
  content: "";
  width: 50px; /* here and you don't need "flex: 1" in this case */
  height: 2px;
  background-color: #990000;
}
```

> Edit second question: how remove the dashed line from the bottom of the index.html?

It looks like it's related to `.pagination` class in css, so just remove `border-top: 1px dashed #ffbf00;` from `.pagination` class

> Edit third hr question: with the edit to add the image I have lost the divider line in the tag listing between post segment listing.

Previously, I recommended placing a separator <div> block after [this line](https://github.com/en9inerd/zola-hacker/blob/c48f02ef2915c93c2ddb579a6994db897ab4e156/templates/index.html#L26)
However, it might be better to place the separator <div> block after [this line](https://github.com/en9inerd/zola-hacker/blob/c48f02ef2915c93c2ddb579a6994db897ab4e156/templates/macros.html#L25) to ensure it affects all templates where the post listing occurs
